
pool:
  vmImage: 'ubuntu-16.04'

pr:
  branches:
    include:
    - master

  paths:
    include:
    - ServiceGroups/*

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "10.x"
  displayName: Install node 10

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'ServiceGroups'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ServiceGroups'
    customCommand: 'run test'
    