
pool:
  vmImage: 'ubuntu-16.04'

trigger:
  branches:
    include:
    - master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "10.x"
  displayName: Install node 10

- script: npm install
  displayName: npm install

- script: npm run test
  displayName: npm run test
